name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: |
          echo Hello World
          java -version
          javac -version
          javac -cp "junit-4.10.jar:." *.java
  calcadd:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Add
        run: |
          javac -cp "junit-4.10.jar:." *.java
          java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestAdd
  calcadd:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Sub
        run: |
          javac -cp "junit-4.10.jar:." *.java
          java -cp "junit-4.10.jar:." org.junit.runner.JUnitCore TestAdd
